# Site settings
title: InfoEducație Blog
email: contact@infoeducatie.ro
description: > # this means to ignore newlines until "baseurl:"
  Blogul InfoEducație. Știri și articole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.infoeducatie.ro" # the base hostname & protocol for your site
twitter_username: infoeducatie
github_username:  infoeducatie

# Build settings
markdown: kramdown
